# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

palette = 'ramos'

[palettes.ramos]
white = "#dcd7ba"      # 15
red = "#e82424"        # 9
purple = "#938aa9"     # 13
yellow = "#e6c384"     # 11
accent = "#c8c093"     # 7
orange = "#c0a36e"     # 3

[character]
success_symbol = '[❯](bold orange)'

[directory]
style = 'bold accent'

[git_branch]
style = 'bold orange'

[git_status]
style = 'bold accent'

[conda] 
style = 'bold orange'
ignore_base = true

[lua]
style = 'bold purple'

[package]
style = 'bold orange'

[zig]
symbol = '⚡️ '
style = 'bold yellow'

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold white)'
